version: '3.8'

services:
  mysql:
    container_name: mysql_container
    image: mysql:8.1
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_USER: mozammil
      MYSQL_PASSWORD: mozammil
      TZ: Asia/Kolkata
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init-db:/docker-entrypoint-initdb.d
    networks:
      - backend
    restart: unless-stopped

  mongo:
    container_name: mongo_container
    image: mongo:6.0
    environment:
      MONGO_INITDB_ROOT_USERNAME: mozammil
      MONGO_INITDB_ROOT_PASSWORD: mozammil
      TZ: Asia/Kolkata
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - backend
    restart: unless-stopped

volumes:
  mysql_data:
  mongo_data:

networks:
  backend:
