CREATE DATABASE IF NOT EXISTS orderdb;
CREATE DATABASE IF NOT EXISTS product;

GRANT ALL PRIVILEGES ON orderdb.* TO 'mozammil'@'%';
GRANT ALL PRIVILEGES ON product.* TO 'mozammil'@'%';
FLUSH PRIVILEGES;
