spring:
  application:
    name:
      order-service
  datasource:
    url: jdbc:mysql://localhost:3307/orderdb
    username: mozammil
    password: mozammil
    driver-class-name: com.mysql.cj.jdbc.Driver

  cloud:
    stream:
      bindings:
        createOrder-out-0:
          destination: order.exchange
          content-type: application/json

      rabbit:
        bindings:
          createOrder-out-0:
            producer:
              routing-key-expression: '''order.tracking'''

  #RabbitMQ configuration
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:mozammil}
    password: ${RABBITMQ_PASSWORD:mozammil}
    virtual-host: ${RABBITMQ_VHOST:/}
    connection-timeout: 30000

  jpa:
    database: MYSQL
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect

server:
  port: 8083

rabbitmq:
  exchange:
    name: order.exchange
  queue:
    name: order.queue
  routing:
    key: order.tracking


management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  health:
    circuitbreakers:
      enabled: true
  tracing:
    sampling:
      probability: 1.0

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

logging:
  file:
    name: logs/${spring.application.name}.log
  logback:
    rollingpolicy:
      max-file-size: 5MB
      max-history: 7

#Circuit Breaker Configuratio
resilience4j:
  circuitbreaker:
    instances:
      productService:
        registerHealthIndicator: true
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        permittedNumberOfCallsInHalfOpenState: 3
        waitDurationInOpenState: 10s
        failureRateThreshold: 50
        automaticTransitionFromOpenToHalfOpenEnabled: true
        slidingWindowType: count_based
  retry:
    instances:
      retryBreaker:
        maxAttempts: 5
        waitDuration: 500ms

  ratelimiter:
    instances:
      reteBreaker:
        timeout-duration: 0
        limit-refresh-period: 4s
        limit-for-period: 2